name: Code Review Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  codeql-analysis:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript,java,python'  # Specify the languages here based on your project

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  provide-feedback:
    needs: codeql-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Provide feedback on PR
        uses: unsplash/comment-on-pr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRETFORSCDASSIGNMENT2 }}
        with:
          msg: 'CodeQL analysis completed. Please check the Security tab for potential vulnerabilities.'
